version: '2'
services:
  coderunner:
    build: coderunner
    ports:
      - "8085:3000"
  db:
    image: postgres:alpine
    expose:
     - 5432
    environment:
     - POSTGRES_PASSWORD=my_password
  cache:
    image: redis:alpine
  railsbackadmin:
    build: railsbackadmin
    ports:
      - "8082:3000"
    command: rails server -b 0.0.0.0
    depends_on:
      - db
  sharedb:
    build: sharedb-ta
    ports:
      - "8083:8080"
  socket_backend:
    build: socket_backend
    ports:
      - "8081:8080"
  template_engine:
    build: template_engine
    ports:
      - "8084:8080"
  leet-front:
    build: leet-front
    ports:
      - "8080:3000"
    depends_on:
      - coderunner
      - railsbackadmin
      - sharedb
      - socket_backend
      - template_engine
