version: '2'
services:
  coderunner:
    build: coderunner
    ports:
      - "8085:3000"
    restart: always
  db:
    image: postgres:alpine
    expose:
     - 5432
    restart: always
    environment:
     - POSTGRES_PASSWORD=my_password
  railsbackadmin:
    build: railsbackadmin
    ports:
      - "8082:3000"
    command: rails server -b 0.0.0.0
    expose:
      - 3000
    restart: always
    depends_on:
      - db
  sharedb:
    build: sharedb-ta
    ports:
      - "8083:8080"
    restart: always
  socket_backend:
    build: socket_backend
    ports:
      - "8081:8080"
    restart: always
  template_engine:
    build: template_engine
    ports:
      - "8084:8080"
    restart: always
  leet-front:
    build: leet-front
    expose:
      - 3000
    restart: always
    depends_on:
      - coderunner
      - railsbackadmin
      - sharedb
      - socket_backend
      - template_engine
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - leet-front
      - railsbackadmin
