default: &default
  adapter: mysql2
  encoding: utf8
  database: leet
  host: db
  port: 3306
  pool: 5
  username: root
  password: my_password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
