default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: my_password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
